import ProductIcon, { type ProductIconName } from "@/components/ProductIcon";

const cases: Array<{ icon: ProductIconName; label: string; title: string; body: string; points: string[] }> = [
  { icon: "captions", label: "For creators", title: "Publish without the post-production drag.", body: "Go from a raw talking video to captions, clips, hooks, and platform-ready copy while the idea is still fresh.", points: ["Vertical, square & landscape", "Karaoke word highlights", "Hooks and title variations"] },
  { icon: "clips", label: "For content teams", title: "Find the usable moment before the meeting ends.", body: "Search long interviews by meaning, share clean transcripts, and reopen every project from one organized workspace.", points: ["Natural-language moment search", "Project folders and history", "SRT, VTT and MP4 exports"] },
  { icon: "translate", label: "For global stories", title: "Make one conversation travel further.", body: "Preserve meaning and timing across languages, then adapt the same source into the format each audience expects.", points: ["Ten translation languages", "Timestamp-preserving exports", "Channel-specific repurposing"] },
];

export default function CreatorUseCases() {
  return <section className="bg-[#f4f1ea] px-5 py-24 sm:px-10"><div className="mx-auto max-w-7xl"><header className="mx-auto max-w-3xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.24em] text-[#087cab]">Made for the work after record</p><h2 className="mt-4 text-4xl font-semibold leading-[1] tracking-[-.05em] sm:text-6xl">Different teams.<br/>The same creative momentum.</h2></header><div className="mt-14 grid gap-4 lg:grid-cols-3">{cases.map((item, index) => <article key={item.label} className={`group flex min-h-[460px] flex-col justify-between overflow-hidden rounded-[30px] border border-black/10 p-7 transition hover:-translate-y-1 sm:p-9 ${index === 1 ? "bg-[#151517] text-white" : "bg-white text-[#151517]"}`}><div><div className={`grid h-12 w-12 place-items-center rounded-2xl ${index === 1 ? "bg-[#75d6ff] text-[#151517]" : "bg-[#151517] text-[#75d6ff]"}`}><ProductIcon name={item.icon}/></div><p className={`mt-9 text-[10px] font-bold uppercase tracking-[.2em] ${index === 1 ? "text-[#75d6ff]" : "text-[#087cab]"}`}>{item.label}</p><h3 className="mt-3 text-3xl font-semibold leading-[1.05] tracking-[-.045em]">{item.title}</h3><p className={`mt-5 text-[13px] leading-6 ${index === 1 ? "text-white/48" : "text-[#6b6761]"}`}>{item.body}</p></div><ul className={`mt-10 space-y-3 border-t pt-6 text-[11px] font-medium ${index === 1 ? "border-white/10 text-white/60" : "border-black/10 text-black/55"}`}>{item.points.map((point) => <li key={point} className="flex items-center gap-3"><span className="h-1.5 w-1.5 rounded-full bg-[#4abce9]"/>{point}</li>)}</ul></article>)}</div></div></section>;
}
