import type { CaptionStyle } from "./subtitles";

/**
 * Trending caption looks. A preset sets everything except canvas aspect and
 * placement, which stay whatever the user chose.
 */
export interface CaptionPreset {
  id: string;
  name: string;
  tag: string;
  style: Omit<CaptionStyle, "preset" | "aspect" | "placement">;
}

export const CAPTION_PRESETS: CaptionPreset[] = [
  {
    id: "clean",
    name: "Clean",
    tag: "Timeless",
    style: {
      font: "Inter",
      color: "#ffffff",
      highlightColor: "#5ac8fa",
      size: 54,
      karaoke: "fill",
      uppercase: false,
      bold: true,
      outline: 3,
      outlineColor: "#000000",
      shadow: 1,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "beast",
    name: "Beast",
    tag: "MrBeast style",
    style: {
      font: "Impact",
      color: "#ffffff",
      highlightColor: "#ffd400",
      size: 74,
      karaoke: "pop",
      uppercase: true,
      bold: true,
      outline: 6,
      outlineColor: "#000000",
      shadow: 2,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "hormozi",
    name: "Hormozi",
    tag: "Podcast clips",
    style: {
      font: "Roboto",
      color: "#ffffff",
      highlightColor: "#3bff6f",
      size: 64,
      karaoke: "pop",
      uppercase: true,
      bold: true,
      outline: 5,
      outlineColor: "#000000",
      shadow: 2,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "wordpop",
    name: "Word Pop",
    tag: "One word at a time",
    style: {
      font: "Impact",
      color: "#ffffff",
      highlightColor: "#ffffff",
      size: 88,
      karaoke: "word",
      uppercase: true,
      bold: true,
      outline: 6,
      outlineColor: "#000000",
      shadow: 2,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "karaoke",
    name: "Karaoke",
    tag: "Sweep fill",
    style: {
      font: "Inter",
      color: "#9aa0a6",
      highlightColor: "#ffffff",
      size: 56,
      karaoke: "fill",
      uppercase: false,
      bold: true,
      outline: 3,
      outlineColor: "#000000",
      shadow: 1,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "bubble",
    name: "Bubble",
    tag: "Reels favorite",
    style: {
      font: "Lato",
      color: "#111111",
      highlightColor: "#111111",
      size: 52,
      karaoke: "off",
      uppercase: false,
      bold: true,
      outline: 4,
      outlineColor: "#ffffff",
      shadow: 0,
      box: true,
      boxColor: "#ffffff",
      glow: false,
    },
  },
  {
    id: "neon",
    name: "Neon",
    tag: "Glow",
    style: {
      font: "Inter",
      color: "#ffffff",
      highlightColor: "#ff2d95",
      size: 58,
      karaoke: "pop",
      uppercase: true,
      bold: true,
      outline: 2,
      outlineColor: "#ff2d95",
      shadow: 0,
      box: false,
      boxColor: "#000000",
      glow: true,
    },
  },
  {
    id: "shorts",
    name: "Shorts Bold",
    tag: "Fast hooks",
    style: {
      font: "Inter",
      color: "#ffffff",
      highlightColor: "#ffd60a",
      size: 72,
      karaoke: "pop",
      uppercase: true,
      bold: true,
      outline: 5,
      outlineColor: "#000000",
      shadow: 2,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "podcast",
    name: "Podcast Box",
    tag: "Long dialogue",
    style: {
      font: "Open Sans",
      color: "#ffffff",
      highlightColor: "#7dd3fc",
      size: 54,
      karaoke: "fill",
      uppercase: false,
      bold: true,
      outline: 0,
      outlineColor: "#000000",
      shadow: 0,
      box: true,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "explainer",
    name: "Explainer",
    tag: "Education",
    style: {
      font: "Lato",
      color: "#ffffff",
      highlightColor: "#67e8f9",
      size: 58,
      karaoke: "fill",
      uppercase: false,
      bold: true,
      outline: 3,
      outlineColor: "#111827",
      shadow: 1,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "breaking",
    name: "Breaking",
    tag: "News updates",
    style: {
      font: "Roboto",
      color: "#ffffff",
      highlightColor: "#ff453a",
      size: 62,
      karaoke: "pop",
      uppercase: true,
      bold: true,
      outline: 4,
      outlineColor: "#000000",
      shadow: 2,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
  {
    id: "playful",
    name: "Playful",
    tag: "Comedy & reels",
    style: {
      font: "Comic Neue",
      color: "#ffffff",
      highlightColor: "#ff66c4",
      size: 66,
      karaoke: "pop",
      uppercase: false,
      bold: true,
      outline: 5,
      outlineColor: "#5b21b6",
      shadow: 2,
      box: false,
      boxColor: "#000000",
      glow: false,
    },
  },
];

export function applyPreset(current: CaptionStyle, preset: CaptionPreset): CaptionStyle {
  return {
    ...current,
    ...preset.style,
    preset: preset.id,
    aspect: current.aspect,
    placement: current.placement,
  };
}
